development:
  adapter: postgresql
  encoding: unicode
  database: Books
  username: postgres
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: Books
  host: localhost
  pool: 5
  username: postgres
  password: 1234

test:
 adapter: postgresql
 encoding: unicode
 pool: 5
 host: localhost
 database: Books_test
 username: postgres
 password: 1234